variables:
  AZCOPY_GOLANG_VERSION: '1.21.8'

parameters:
  - name: publish_to_container
    displayName: 'Publish To Container'
    type: boolean
    default: false

  - name: publish_to_m1_container
    displayName: 'Publish To M1 Container'
    type: boolean
    default: false

# Do not trigger this pipeline automatically
trigger: none
pr: none

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: azcopy-pool  # Name of your hosted pool
        image: windows2022-1espt
        os: windows  # OS of the image. Allowed values: windows, linux, macOS
    stages:
      - stage: ReleaseToContainer
        jobs:
          - job: Upload
            pool:
              name: azcopy-pool
              image: ubuntu22-1espt
              os: linux
            # If the pipeline publishes artifacts, use `templateContext` to define the artifacts.
            # This will enable 1ES PT to run SDL analysis tools on the artifacts and then upload them.
              pool:
                name: azcopy-pool
                image: ubuntu22-1espt
                os: linux
              variables:
                - name: test_release_account_name
                  value: 'azcopyprivatedrops'
                - name: release_account_name
                  value: 'azcopyvnextrelease'
                - name: publish_container
                  value: ${{ parameters.publish_to_container }}
                - name: publish_m1_container
                  value: ${{ parameters.publish_to_m1_container }}
                - name: input_path
                  value: $(System.DefaultWorkingDirectory)
                - name: drop
                  value: $(System.DefaultWorkingDirectory)/drop
                - name: release
                  value: $(System.DefaultWorkingDirectory)/release

              steps:
                - checkout: self
                  displayName: 'Checkout repository'

                - script: |
                    go build -tags "netgo" -o ./azcopy
                  displayName: 'Install azcopy'

                - script : |
                    mkdir -p $(release)
                  displayName: 'Prepare release folder'

                - script : |
                    mkdir -p $(drop)
                  displayName: 'Prepare drop.zip folder'

                - task: ArchiveFiles@2
                  displayName: 'Archive drop.zip'
                  inputs:
                    rootFolderOrFile: '$(drop)'
                    archiveFile: '$(release)/drop.zip'

                - task: AzureCLI@2
                  displayName: 'Azure CLI'
                  inputs:
                    azureSubscription: 'ESRP KeyVault identity'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      today=$(date +"%Y%m%d")
                      
                      if [ $(publish_container) = "True" ]; then
                        container_url="https://$(release_account_name).blob.core.windows.net/%24web/releases/release-$(azcopy_version)-$today"
                      else
                        container_url="https://$(test_release_account_name).blob.core.windows.net/%24web/releases/release-$(azcopy_version)-$today"
                      fi
                      echo "Artifacts will be uploaded to: $container_url"
                      
                      # Upload the archived builds
                      AZCOPY_AUTO_LOGIN_TYPE=AzCLI ./azcopy cp "$(release)/*" "$container_url" --recursive --put-md5=true
                      
                      if [ $(publish_m1_container) = "True" ]; then
                        m1_container_url="https://$(release_account_name).blob.core.windows.net/%24web/azcopy-m1-drops/azcopy-$(azcopy_version)-$today"
                        AZCOPY_AUTO_LOGIN_TYPE=AzCLI ./azcopy cp "$(input_path)/azcopy-binaries-mac/azcopy_darwin_m1_arm64" "$m1_container_url" --put-md5=true
                      fi